[package]
name = "novafetch"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4", features = ["derive"] }
colored = "2.1"
dirs = "5"
serde = { version = "1", features = ["derive"] }
sysinfo = "0.38"
toml = "0.8"
whoami = "1.4"
